BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "BatchAccounts" (
	"batchID"	TEXT,
	"EID"	TEXT,
	"BID"	TEXT UNIQUE,
	"UID"	TEXT UNIQUE,
	"AccountName"	TEXT,
	"brand"	TEXT,
	"currency"	TEXT,
	"SpendingLimit"	NUMBER,
	PRIMARY KEY("EID")
);
CREATE TABLE IF NOT EXISTS "BatchDescription" (
	"name"	TEXT,
	"description"	TEXT,
	"accSizeMin"	INTEGER,
	"accSizeMax"	INTEGER,
	"brand"	TEXT,
	"telcoProvider"	TEXT,
	"seatEdition"	TEXT,
	"accountList"	TEXT,
	"casesMin"	INTEGER,
	"casesMax"	INTEGER,
	"casesNBU"	TEXT,
	"maxSize"	INTEGER,
	"ContactCenterMRR"	NUMBER,
	"totalMRR"	NUMBER,
	"timestamp"	TEXT,
	"PaymentPlan"	TEXT,
	"AccountPaymentMethod"	TEXT,
	"AnnualMonth"	INTEGER,
	PRIMARY KEY("name")
);
CREATE TABLE IF NOT EXISTS "BatchEntitlements" (
	"EID"	TEXT,
	"UID"	TEXT,
	"BID"	TEXT,
	"AccountName"	TEXT,
	"ID"	TEXT,
	"EXT_PRODUCT_ID"	TEXT,
	"ITEM_NAME"	TEXT,
	"ITBS_NAME"	TEXT,
	"RETAIL_PRICE"	NUMBER,
	"MDURATION"	INTEGER,
	"CURRENCY_CODE"	TEXT,
	"OldPrice"	NUMBER,
	"OldQntyThreshold"	INTEGER,
	"QNTY_THRESHOLD"	INTEGER,
	"PriceUSD"	NUMBER,
	"PriceCAD"	NUMBER,
	"PriceAUD"	NUMBER,
	"PriceEUR"	NUMBER,
	"PriceGBP"	NUMBER,
	"DiscountUSD"	NUMBER,
	"DiscountCAD"	NUMBER,
	"DiscountAUD"	NUMBER,
	"DiscountEUR"	NUMBER,
	"DiscountGBP"	NUMBER,
	"NiCPrice"	NUMBER,
	"Category"	TEXT,
	"PARENT"	TEXT,
	"ProductFamily"	TEXT,
	"Ratio"	NUMBER,
	"batchID"	TEXT
);
CREATE TABLE IF NOT EXISTS "CatalogSFDC" (
	"No"	INTEGER,
	"L_CATEGORY"	TEXT,
	"PRODUCT_NAME"	TEXT,
	"PRODUCT_FAMILY"	TEXT,
	"PARENT"	TEXT,
	"PRICE_USD"	NUMERIC,
	"PRICE_CAD"	NUMERIC,
	"SKU"	TEXT,
	"NIC_NAME"	TEXT,
	"NIC_PRICE"	NUMERIC,
	"INSERTED"	TEXT,
	"PRICE_AUD"	NUMERIC,
	"PRICE_EUR"	NUMERIC,
	"PRICE_GBP"	BLOB,
	PRIMARY KEY("L_CATEGORY","No")
);
CREATE TABLE IF NOT EXISTS "Entitlements" (
	"USERID"	INTEGER,
	"ID"	INTEGER,
	"START_DATE"	TEXT,
	"END_DATE"	TEXT,
	"COUNTRY_ID"	INTEGER,
	"COUNTRY_NAME"	TEXT,
	"BILLING_ITEM_ID"	INTEGER,
	"EXT_PRODUCT_ID"	TEXT,
	"ITEM_NAME"	TEXT,
	"RETAIL_PRICE"	INTEGER,
	"DISCOUNT_VALUE"	REAL,
	"DISCOUNT_TYPE"	TEXT,
	"QNTY_THRESHOLD"	INTEGER,
	"PRODUCTFAMILY"	TEXT,
	"STATUS_NAME"	TEXT,
	"MDURATION"	INTEGER,
	"CURRENCY_CODE"	TEXT,
	"RAMPUP_START"	TEXT,
	"RAMPUP_END"	TEXT
);
CREATE TABLE IF NOT EXISTS "Entitlements_DWH" (
	"USERID"	TEXT,
	"ID"	INTEGER,
	"START_DATE"	TEXT,
	"END_DATE"	TEXT,
	"COUNTRY_ID"	INTEGER,
	"COUNTRY_NAME"	TEXT,
	"BILLING_ITEM_ID"	INTEGER,
	"EXT_PRODUCT_ID"	TEXT,
	"ITEM_NAME"	TEXT,
	"RETAIL_PRICE"	NUMERIC,
	"DISCOUNT"	NUMERIC,
	"DISCOUNT_TYPE"	TEXT,
	"DISCOUNT_VALUE"	NUMERIC,
	"QNTY_THRESHOLD"	NUMERIC,
	"ProductFamily"	TEXT,
	"STATUS_NAME"	TEXT,
	"MDURATION"	INTEGER,
	"CURRENCY_CODE"	TEXT,
	"RAMPUP_START"	TEXT,
	"RAMPUP_END"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Entitlements_DWH_backup" (
	"USERID"	TEXT,
	"ID"	INTEGER,
	"START_DATE"	TEXT,
	"END_DATE"	TEXT,
	"COUNTRY_ID"	INTEGER,
	"COUNTRY_NAME"	TEXT,
	"BILLING_ITEM_ID"	INTEGER,
	"EXT_PRODUCT_ID"	TEXT,
	"ITEM_NAME"	TEXT,
	"RETAIL_PRICE"	NUMERIC,
	"DISCOUNT"	NUMERIC,
	"DISCOUNT_TYPE"	TEXT,
	"DISCOUNT_VALUE"	NUMERIC,
	"QNTY_THRESHOLD"	NUMERIC,
	"ProductFamily"	TEXT,
	"STATUS_NAME"	TEXT,
	"MDURATION"	INTEGER,
	"CURRENCY_CODE"	TEXT,
	"RAMPUP_START"	TEXT,
	"RAMPUP_END"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "RCMRCSummary" (
	"Account"	TEXT,
	"Customer"	TEXT,
	"Address1"	TEXT,
	"Address2"	TEXT,
	"City"	TEXT,
	"State"	TEXT,
	"ZipCode"	TEXT,
	"Invoice"	TEXT,
	"BillingPeriodStart"	TEXT,
	"BillingPeriodEnd"	TEXT,
	"InvoiceDate"	TEXT,
	"DueDate"	TEXT,
	"ProductType"	TEXT,
	"CatalogID"	TEXT,
	"FeatureID"	TEXT,
	"FeatureDetailID"	TEXT,
	"Product"	TEXT,
	"Quantity"	TEXT,
	"Amount"	TEXT
);
CREATE TABLE IF NOT EXISTS "ScreenRecordingAudit" (
	"Date"	TEXT,
	"Account"	TEXT,
	"Account ID"	INTEGER,
	"UII"	REAL,
	"Call Type"	TEXT,
	"Segment Index"	INTEGER,
	"Interaction Start Time"	TEXT,
	"Interaction End Time"	TEXT,
	"Channel Type"	TEXT,
	"Dial Type"	TEXT,
	"ANI"	INTEGER,
	"DNIS"	INTEGER,
	"Product"	TEXT,
	"Product ID"	INTEGER,
	"Product Type"	TEXT,
	"Agent Full Name"	TEXT,
	"Agent Disposition"	TEXT,
	"Transfer Type"	TEXT,
	"Agent Transfer Destination Source Type"	TEXT,
	"Call Result"	TEXT,
	"Term Party"	TEXT,
	"Term Reason"	TEXT,
	"Recording URL"	TEXT,
	"Voicemail Recording URL"	TEXT,
	"Screen Recording URL"	TEXT,
	"RNA"	TEXT,
	"Queue Time (min)"	INTEGER,
	"Ring Time (min)"	INTEGER,
	"Outbound Ring Time (min)"	INTEGER,
	"Handle Time (min)"	INTEGER,
	"Talk Time (min)"	INTEGER,
	"Wrap Time (min)"	INTEGER,
	"Interaction Time (min)"	INTEGER
);
CREATE TABLE IF NOT EXISTS "ScreenRecordings" (
	"Account"	TEXT,
	"Date"	TEXT,
	"UII"	REAL,
	"Call Type"	TEXT,
	"Segment Index"	INTEGER,
	"Interaction Start Time"	TEXT,
	"Interaction End Time"	TEXT,
	"Channel Type"	TEXT,
	"Dial Type"	TEXT,
	"ANI"	TEXT,
	"DNIS"	TEXT,
	"Product"	TEXT,
	"Product ID"	INTEGER,
	"Product Type"	TEXT,
	"Agent Full Name"	TEXT,
	"Agent Disposition"	TEXT,
	"Transfer Type"	TEXT,
	"Agent Transfer Destination Source Type"	TEXT,
	"Call Result"	TEXT,
	"Term Party"	TEXT,
	"Term Reason"	TEXT,
	"Recording URL"	TEXT,
	"Screen Recording URL"	TEXT,
	"Voicemail Recording URL"	TEXT,
	"RNA"	TEXT,
	"Queue Time (min)"	INTEGER,
	"Ring Time (min)"	INTEGER,
	"Outbound Ring Time (min)"	INTEGER,
	"Handle Time (min)"	INTEGER,
	"Talk Time (min)"	INTEGER,
	"Wrap Time (min)"	INTEGER,
	"Interaction Time (min)"	INTEGER
);
CREATE TABLE IF NOT EXISTS "account_contact_info" (
	"EID"	TEXT,
	"email"	TEXT,
	"phone"	TEXT,
	PRIMARY KEY("EID")
);
CREATE TABLE IF NOT EXISTS "accounts_sfdc" (
	"InContactBUID"	INTEGER,
	"EnterpriseAccountID"	INTEGER,
	"BillingID"	INTEGER,
	"AccountID"	TEXT,
	"AccountName"	TEXT,
	"Servicename"	TEXT,
	"AccountPaymentMethod"	TEXT,
	"PaymentPlan"	TEXT,
	"Brand"	TEXT,
	"inContactCluster"	TEXT,
	"ContactCenterNumbersLocation"	TEXT,
	"AgentlegSIPconfig"	TEXT,
	"OutboundTransport"	TEXT,
	"ImplementationCompleteDate"	TEXT,
	"ProvisionDate"	TEXT,
	"BillAsOfDate"	TEXT,
	"ImplementationContact"	TEXT,
	"No.ofInContactSeats"	INTEGER,
	"CurrentOwner"	TEXT,
	"CurrentOwnerEmail"	TEXT,
	"CurrentOwnerManagerEmail"	TEXT,
	"CSM"	TEXT,
	"InContactService"	TEXT,
	"PriceperSeatCurrency"	TEXT,
	"PriceperSeat"	NUMERIC,
	"PaymentMethod"	TEXT,
	"ContactCenterMRR"	NUMERIC,
	"CurrentTotalMRRconverted"	NUMERIC,
	"BillingStreet"	TEXT,
	"BillingCity"	TEXT,
	"BillingState"	TEXT,
	"BillingZipCode"	TEXT,
	"BillingCountry"	TEXT,
	"Timezone"	TEXT,
	"CCStartDate"	TEXT,
	"CCEndDate"	TEXT,
	"SalesAgreementStartDate"	TEXT,
	"SalesAgreementEndDate"	TEXT,
	"NextBillDate"	TEXT,
	PRIMARY KEY("EnterpriseAccountID")
);
CREATE TABLE IF NOT EXISTS "accounts_sfdc_backup" (
	"InContactBUID"	INTEGER,
	"EnterpriseAccountID"	INTEGER,
	"BillingID"	INTEGER,
	"AccountID"	TEXT,
	"AccountName"	TEXT,
	"Servicename"	TEXT,
	"AccountPaymentMethod"	TEXT,
	"PaymentPlan"	TEXT,
	"Brand"	TEXT,
	"inContactCluster"	TEXT,
	"ContactCenterNumbersLocation"	TEXT,
	"AgentlegSIPconfig"	TEXT,
	"OutboundTransport"	TEXT,
	"ImplementationCompleteDate"	TEXT,
	"ProvisionDate"	TEXT,
	"BillAsOfDate"	TEXT,
	"ImplementationContact"	TEXT,
	"No.ofInContactSeats"	INTEGER,
	"CurrentOwner"	TEXT,
	"CurrentOwnerEmail"	TEXT,
	"CurrentOwnerManagerEmail"	TEXT,
	"CSM"	TEXT,
	"InContactService"	TEXT,
	"PriceperSeatCurrency"	TEXT,
	"PriceperSeat"	NUMERIC,
	"PaymentMethod"	TEXT,
	"ContactCenterMRR"	NUMERIC,
	"CurrentTotalMRRconverted"	NUMERIC,
	"BillingStreet"	TEXT,
	"BillingCity"	TEXT,
	"BillingState"	TEXT,
	"BillingZipCode"	TEXT,
	"BillingCountry"	TEXT,
	"Timezone"	TEXT,
	"CCStartDate"	TEXT,
	"CCEndDate"	TEXT,
	"SalesAgreementStartDate"	TEXT,
	"SalesAgreementEndDate"	TEXT,
	"NextBillDate"	TEXT,
	PRIMARY KEY("EnterpriseAccountID")
);
CREATE TABLE IF NOT EXISTS "invoiceLines" (
	"CCBID"	INTEGER,
	"USERID"	INTEGER,
	"INC_ACCOUNTID"	INTEGER,
	"BRANDID"	INTEGER,
	"BRANDNAME"	TEXT,
	"BILLING_MONTH"	TEXT,
	"BILLING_DATE"	TEXT,
	"TOTAL_AMOUNT"	NUMBER,
	"EXT_PRODUCT_ID"	TEXT,
	"NSBID"	INTEGER,
	"BILLINGITEMID"	INTEGER,
	"CCBITEMID"	INTEGER,
	"ITEMNAME"	TEXT,
	"ENTITLEMENT_LOG_ID"	INTEGER,
	"ITEM_PRICE"	NUMBER,
	"QUANTITY"	NUMBER,
	"ITEM_DISC"	NUMBER,
	"AMOUNT"	NUMBER,
	"TAX_TRANS_TYPE"	TEXT,
	"TAX_SVC_TYPE"	TEXT,
	"TAX_AMOUNT"	NUMBER,
	"VSOE_PRICE"	NUMBER,
	PRIMARY KEY("USERID","BILLING_MONTH","ENTITLEMENT_LOG_ID")
);
CREATE TABLE IF NOT EXISTS "invoices" (
	"CCBID"	TEXT,
	"USERID"	TEXT,
	"INC_ACCOUNTID"	TEXT,
	"BRANDID"	TEXT,
	"BRANDNAME"	TEXT,
	"SERVICELEVEL"	TEXT,
	"ACCOUNTSTATUSID"	TEXT,
	"BILLING_MONTH"	TEXT,
	"BILLING_DATE"	TEXT,
	"CURRENCYID"	TEXT,
	"TOTAL_AMOUNT"	TEXT,
	"ADMINID"	TEXT,
	"TS_INSERTED"	TEXT,
	"TS_UPDATED"	TEXT,
	"PLAN_PAYMENTTYPEID"	TEXT,
	PRIMARY KEY("USERID","BILLING_MONTH")
);
CREATE TABLE IF NOT EXISTS "itbs_ngbs_maps" (
	"itbs_ext_product_id"	TEXT,
	"itbs_license_name"	TEXT,
	"itbs_license_type"	TEXT,
	"ngbs_package_id"	INTEGER,
	"ngbs_license_id"	TEXT,
	"ratio"	INTEGER
);
CREATE TABLE IF NOT EXISTS "nic_case_items" (
	"accountID"	TEXT,
	"BUID"	TEXT,
	"sfdcCase"	TEXT,
	"operation"	TEXT,
	"skuid"	TEXT,
	"sku"	TEXT,
	"qtty"	REAL,
	"price"	REAL,
	PRIMARY KEY("sfdcCase","operation","skuid")
);
CREATE TABLE IF NOT EXISTS "nic_cases" (
	"ICCaseNumber"	INTEGER,
	"inContactBUID"	INTEGER,
	"UID"	INTEGER,
	"AccountName"	TEXT,
	"Subject"	TEXT,
	"OrderNumber"	INTEGER,
	"OrderID"	TEXT,
	"CaseNumber"	INTEGER,
	"Description"	TEXT,
	"SubmittedDate"	TEXT,
	"ProvisionDate"	TEXT,
	"OrderType"	TEXT,
	"Status"	TEXT,
	"OpportunityName"	TEXT,
	"Brand"	TEXT,
	"NoOfInContactSeats"	INTEGER,
	"ImplementationTeam"	TEXT,
	"ContactCenterNumber"	TEXT,
	"GeoRegion"	TEXT,
	"DefaultTimeZone"	TEXT,
	"CreatedDate"	TEXT,
	"DBInserted"	TEXT,
	PRIMARY KEY("ICCaseNumber")
);
COMMIT;
